// <auto-generated />
namespace Ninja.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTokenAndPassword : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTokenAndPassword));
        
        string IMigrationMetadata.Id
        {
            get { return "201710030859367_AddTokenAndPassword"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
